# Data Cleaning part II

After gathering and combining the tweets, it was important to remove null values in order to create a VADER-based sentiment analysis for data exploration.

In [1]:
import pandas as pd  
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
pd.read_csv('depressive_unigram_tweets_final.csv')

/Users/anneb/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,1,2,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Unnamed: 0.1,cashtags,hashtags,id,time,tweet
0,0,0,[],[],1.15135E+18,21:25:13,"Wow, my dad yday: “you don’t take those stupid..."
1,1,1,[],[],1.15135E+18,21:25:07,what part of this was really harmfult of a lot...
2,2,2,[],"['#depression', '#uncoveringthenewu', '#change...",1.15135E+18,21:25:06,one of the ways I got through my #depression i...
3,3,3,[],[],1.15135E+18,21:24:55,see i wanna do one of them but they all say th...
4,4,4,[],[],1.15135E+18,21:24:51,IS IT clinical depression or is it the palpabl...
5,5,5,[],[],1.15135E+18,21:24:46,My new mantra for dealing with my anxiety/depr...
6,6,6,[],[],1.15135E+18,21:24:41,Can I get a woot woot for 3 months depression ...
7,7,7,[],[],1.15135E+18,21:24:37,Hope it's working for you. I was on sertralin...
8,8,8,[],[],1.15135E+18,21:24:22,When my depression and anxiety strike at the s...
9,9,9,[],[],1.15135E+18,21:24:20,"I want to leave, but I'm still waiting for you..."
10,10,10,[],[],1.15135E+18,21:24:07,lrt i have FUCKING DEPRESSION
11,11,11,[],[],1.15135E+18,21:24:07,If you’re a new mother who is tired from postp...
12,12,12,[],[],1.15135E+18,21:24:04,Currently 5:23 and I’ve got depression Ranger...
13,13,13,[],[],1.15135E+18,21:24:01,omg wish I could swim cause I'm gonna drown in...
14,14,14,[],[],1.15135E+18,21:24:00,I don’t talk about it much at all unless you’r...
15,15,15,[],[],1.15135E+18,21:23:55,🚨🚨🚨 If someone can help me by suggesting me ho...
16,16,16,[],[],1.15135E+18,21:23:39,luv 2 just start crying bc you're thinking of ...
17,17,17,[],[],1.15135E+18,21:23:33,yOu cAnT hUrT mE DePrEsSiOn GoT mE AlReAdY
18,18,18,[],[],1.15135E+18,21:23:32,"The free market cab cure your depression, just..."
19,19,19,[],[],1.15135E+18,21:23:31,I’m not steeped enough in the research to have...
20,20,20,[],['#triggerwarning'],1.15135E+18,21:23:28,I feel like I can’t work for more than two to ...
21,21,21,[],[],1.15135E+18,21:23:28,dvdRadio 102 Still looking for a title. (That...
22,22,22,[],[],1.15135E+18,21:23:27,Do you recommend this for every kind of depres...
23,23,23,[],[],1.15135E+18,21:23:26,I was having a bad day and was all depressed. ...
24,24,24,[],[],1.15135E+18,21:23:25,but it completely makes sense tho it a surviva...
25,25,25,[],[],1.15135E+18,21:23:23,For example a top has to know how to deal with...
26,26,26,[],[],1.15135E+18,21:23:17,So. Here is the short and skinny about me here...
27,27,27,[],[],1.15135E+18,21:23:12,me when someone points out my crippling anxiet...
28,28,28,[],[],1.15135E+18,21:23:05,No one: Literally no one: Clair Boucher/ム尺ﾉﾶ...
29,29,29,[],[],1.15135E+18,21:22:52,As a platoon leader I have to deal with that m...
...,...,...,...,...,...,...,...
2783546,225147,NaN,[],[],1.15237e+18,17:02:25,Suicide by oyster is a noble way to go https:...
2783547,225148,NaN,[],[],1.15237e+18,17:02:24,"floors are covered in water, so obviously a cl..."
2783548,225149,NaN,[],[],1.15237e+18,17:02:17,That's a depressingly relatable perspective. ...
2783549,225150,NaN,[],[],1.15237e+18,17:02:15,@glitterndior https://twitter.com/DankNeme/sta...
2783550,225151,NaN,[],[],1.15237e+18,17:02:13,TW for suicide and fatphobia. My mom has seve...
2783551,225152,NaN,[],[],1.15237e+18,17:02:03,« Le professeur meurt et Tokyo se suicide » jl...
2783552,225153,NaN,[],[],1.15237e+18,17:02:02,"Telling a gay youth is choices are suicide, ex..."
2783553,225154,NaN,[],[],1.15237e+18,17:02:01,Tokyo tue professor et se suicide
2783554,225155,NaN,[],[],1.15237e+18,17:02:00,suicide's time :))
2783555,225156,NaN,[],[],1.15237e+18,17:01:58,For Those Considering Suicide https://youtu.b...
2783556,225157,NaN,[],[],1.15237e+18,17:01:54,Tf suicide isn’t no joke https://twitter.com/...
2783557,225158,NaN,[],[],1.15237e+18,17:01:53,It always brings to mind the “body in the bag ...
2783558,225159,NaN,[],"['#suicidesilence', '#youonlyliveonce', '#lege...",1.15237e+18,17:01:45,You only live once so just go fucking nuts!Go!...
2783559,225160,NaN,[],[],1.15237e+18,17:01:40,i cant wait to entrap a woman into a web of vi...
2783560,225161,NaN,[],[],1.15237e+18,17:01:21,고마웠었어 #€
2783561,225162,NaN,[],[],1.15237e+18,17:01:14,The “Clinton Suicide Squad “ is gearing up as ...
2783562,225163,NaN,[],[],1.15237e+18,17:01:14,Last Monday a I had to tell a client his benef...
2783563,225164,NaN,[],[],1.15237e+18,17:01:08,http://bit.ly/MurderOfTalent Why is the publ...
2783564,225165,NaN,[],[],1.15237e+18,17:01:02,戸塚：電車の車内でケータイが鳴った一八木さんが「いま電話の中だから電車切るぞ」って言ってケー...
2783565,225166,NaN,[],[],1.15237e+18,17:00:54,y'a pas d'incruste ti é la famille
2783566,225167,NaN,[],"['#mentalhealth', '#suicideprevention']",1.15237e+18,17:00:52,A study will use CCTV from certain locations t...
2783567,225168,NaN,[],[],1.15237e+18,17:00:41,"Since I was reminded of her today, everyone pl..."
2783568,225169,NaN,[],[],1.15237e+18,17:00:35,Mariko was a quick favorite for me. I'm glad s...
2783569,225170,NaN,[],[],1.15237e+18,17:00:22,pic.twitter.com/sm9tNmrEQJ
2783570,225171,NaN,[],[],1.15237e+18,17:00:18,https://youtu.be/WJ0OkkIDZug Deathnote is r...
2783571,225172,NaN,[],[],1.15237e+18,17:00:17,えっ？！オニィ結構なお歳……（今知った） 変な声でちゃった(笑)
2783572,225173,NaN,[],"['#physicianfriday', '#suicide', '#physicians'...",1.15237e+18,17:00:12,"#PhysicianFriday ""Let's empower doctors to tak..."
2783573,225174,NaN,[],"['#aztrauma', '#traumatraining', '#suicide', '...",1.15237e+18,17:00:01,A spike in suicides among teenage boys in the ...
2783574,225175,NaN,[],[],1.15237e+18,17:00:00,Need some support? Check out the following res...
2783575,225176,NaN,[],[],1.15237e+18,17:00:00,You can improve the quality of life for a frie...

In [3]:
import nltk
nltk.download(['punkt','stopwords'])
from nltk.corpus import stopwords
stopwords = stopwords.words('english')

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

[nltk_data] Downloading package punkt to /Users/anneb/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /Users/anneb/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
df2 = pd.read_csv('depressive_unigram_tweets_final.csv')

/Users/anneb/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,1,2,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
df2.head()

,Unnamed: 0,Unnamed: 0.1,cashtags,hashtags,id,time,tweet
0,0,0,[],[],1.15135E+18,21:25:13,"Wow, my dad yday: “you don’t take those stupid..."
1,1,1,[],[],1.15135E+18,21:25:07,what part of this was really harmfult of a lot...
2,2,2,[],"['#depression', '#uncoveringthenewu', '#change...",1.15135E+18,21:25:06,one of the ways I got through my #depression i...
3,3,3,[],[],1.15135E+18,21:24:55,see i wanna do one of them but they all say th...
4,4,4,[],[],1.15135E+18,21:24:51,IS IT clinical depression or is it the palpabl...

In [6]:
df2.isnull().any().any()

True

In [7]:
df2.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2783576 entries, 0 to 2783575
Data columns (total 7 columns):
Unnamed: 0      2783576 non-null object
Unnamed: 0.1    135497 non-null object
cashtags        1650586 non-null object
hashtags        1650586 non-null object
id              1650612 non-null object
time            1650612 non-null object
tweet           1650599 non-null object
dtypes: object(7)
memory usage: 148.7+ MB

In [8]:
df_new = df2[df2['tweet'].notnull()]

In [9]:
df_new.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1650599 entries, 0 to 2783575
Data columns (total 7 columns):
Unnamed: 0      1650599 non-null object
Unnamed: 0.1    135474 non-null object
cashtags        1650586 non-null object
hashtags        1650586 non-null object
id              1650599 non-null object
time            1650599 non-null object
tweet           1650599 non-null object
dtypes: object(7)
memory usage: 100.7+ MB

In [10]:
df_new.isnull().any().any()

True

In [ ]:
df_new['clean_tweet'] = df_new['tweet'].apply(lambda x: ' '.join([item for item in x.split() if item not in stopwords]))

In [ ]:
df_new.head()

In [ ]:
df_new['vader_score'] = df_new['clean_tweet'].apply(lambda x: analyzer.polarity_scores(x)['compound'])

In [ ]:
df_new.head()

In [ ]:
positive_num = len(df_new[df_new['vader_score'] >=0.05])
#neutral_num = len(df_new[(df_new['vaderReviewScore'] >-0.05) & (df_new['vaderReviewScore']<0.05)])
negative_num = len(df_new[df_new['vader_score']<0.05])

In [ ]:
#positive_num,neutral_num, negative_num
positive_num, negative_num

In [ ]:
positive_num.mean()

In [ ]:
positive_num.median()

In [ ]:
positive_num.mode()

In [17]:
df_new['vader_sentiment_label']= df_new['vader_score'].map(lambda x:int(1) if x>=0.05 else int(0))

/Users/anneb/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [18]:
df_new.head()

,Unnamed: 0,Unnamed: 0.1,cashtags,hashtags,id,time,tweet,clean_tweet,vader_score,vader_sentiment_label
0,0,0,[],[],1.15135E+18,21:25:13,"Wow, my dad yday: “you don’t take those stupid...","Wow, dad yday: “you don’t take stupid depressi...",-0.4122,0
1,1,1,[],[],1.15135E+18,21:25:07,what part of this was really harmfult of a lot...,part really harmfult lot people went every gui...,-0.8074,0
2,2,2,[],"['#depression', '#uncoveringthenewu', '#change...",1.15135E+18,21:25:06,one of the ways I got through my #depression i...,one ways I got #depression learning dance rain...,0.7263,1
3,3,3,[],[],1.15135E+18,21:24:55,see i wanna do one of them but they all say th...,"see wanna one say PTSD, depression, and/or anx...",-0.4588,0
4,4,4,[],[],1.15135E+18,21:24:51,IS IT clinical depression or is it the palpabl...,IS IT clinical depression palpable hopelessnes...,-0.8316,0

In [19]:
#df_new.loc[df_new['vaderReviewScore'] >=0.00,"vaderSentimentLabel"] = 1
#df_new.loc[df_new['vaderReviewScore']<=-0.00,"vaderSentimentLabel"] = 0

In [20]:
df_new.head()

,Unnamed: 0,Unnamed: 0.1,cashtags,hashtags,id,time,tweet,clean_tweet,vader_score,vader_sentiment_label
0,0,0,[],[],1.15135E+18,21:25:13,"Wow, my dad yday: “you don’t take those stupid...","Wow, dad yday: “you don’t take stupid depressi...",-0.4122,0
1,1,1,[],[],1.15135E+18,21:25:07,what part of this was really harmfult of a lot...,part really harmfult lot people went every gui...,-0.8074,0
2,2,2,[],"['#depression', '#uncoveringthenewu', '#change...",1.15135E+18,21:25:06,one of the ways I got through my #depression i...,one ways I got #depression learning dance rain...,0.7263,1
3,3,3,[],[],1.15135E+18,21:24:55,see i wanna do one of them but they all say th...,"see wanna one say PTSD, depression, and/or anx...",-0.4588,0
4,4,4,[],[],1.15135E+18,21:24:51,IS IT clinical depression or is it the palpabl...,IS IT clinical depression palpable hopelessnes...,-0.8316,0

In [22]:
df_new.drop(['Unnamed: 0.1', 'id', 'time', 'tweet', ], axis = 1, inplace = True)

/Users/anneb/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [24]:
df_new = df_new[['Unnamed: 0', 'vader_sentiment_label', 'vader_score', 'clean_tweet']]

In [25]:
df_new.head()

,Unnamed: 0,vader_sentiment_label,vader_score,clean_tweet
0,0,0,-0.4122,"Wow, dad yday: “you don’t take stupid depressi..."
1,1,0,-0.8074,part really harmfult lot people went every gui...
2,2,1,0.7263,one ways I got #depression learning dance rain...
3,3,0,-0.4588,"see wanna one say PTSD, depression, and/or anx..."
4,4,0,-0.8316,IS IT clinical depression palpable hopelessnes...

In [26]:
positive_num = len(df_new[df_new['vader_score'] >=0.05])
neutral_num = len(df_new[(df_new['vader_score'] >-0.05) & (df_new['vader_score']<0.05)])
negative_num = len(df_new[df_new['vader_score']<=-0.05])

In [27]:
positive_num,neutral_num, negative_num

(42745, 1493208, 114646)

In [28]:
df_new.to_csv('vader_processed_final.csv')